apiVersion: apps/v1
kind: Deployment
metadata:
  name: whanos-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: "{{ .Values.image }}"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080