FROM node:latest-alpine

# Install Bourne-Again Shell and Curl
RUN apk add --no-cache bash curl

# Use Bourne-Again Shell
SHELL ["/bin/bash", "-c"]

# Install dependency
RUN npm install befunge93

# Get compiler script
RUN curl -L URLDUFICHIER > /opt/befunge-compiler.js

# Copy files
COPY . /app

# Go to files
WORKDIR /app

# Run befunge
CMD ["node", "/opt/befunge-compiler.js", "app/main.bf"]