FROM node:14.17.5-alpine

# Use Bourne-Again Shell
RUN apk add --no-cache bash

# Use Bourne-Again Shell
SHELL ["/bin/bash", "-c"]

# Copy files
ONBUILD COPY . /app

# Go to folder with files
ONBUILD WORKDIR /app

# Install dependencies
ONBUILD RUN npm install --production=false

# run app
ONBUILD CMD ["node", "."]